#!/usr/bin/env node
// Lab 3 - AI-assisted test generation.
//
//   npm run testgen                 # with ANTHROPIC_API_KEY: writes a draft spec
//   npm run testgen -- --print      # no key needed: prints the prompt to paste
//                                   # into Claude, Copilot Chat or any assistant
//
// The output lands in labs/12-ai-in-qa/testgen/generated/ - NOT in a test folder. It is
// a draft for a human to review with review-checklist.md, then move.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..', '..', '..');
const spec = fs.readFileSync(path.join(root, 'app', 'openapi.yaml'), 'utf8');
const template = fs.readFileSync(path.join(here, 'prompts', 'generate-api-tests.md'), 'utf8');
const prompt = template.replace('{{SPEC}}', spec);

const hasCredentials = process.env.ANTHROPIC_API_KEY || process.env.ANTHROPIC_AUTH_TOKEN;
if (process.argv.includes('--print') || !hasCredentials) {
  if (!hasCredentials && !process.argv.includes('--print')) {
    console.error('No ANTHROPIC_API_KEY set - printing the prompt instead. Paste it into your AI assistant.\n');
  }
  console.log(prompt);
  process.exit(0);
}

const { default: Anthropic } = await import('@anthropic-ai/sdk');
const client = new Anthropic();
const model = process.env.TESTGEN_MODEL || 'claude-opus-5-5';
console.error(`Generating tests with ${model}...`);

const response = await client.beta.messages.create({
  model,
  max_tokens: 16000,
  output_config: { effort: 'medium' },
  // Server-side refusal fallback - the API retries on a fallback model if a
  // safety classifier declines.
  betas: ['server-side-fallback-2026-07-01'],
  fallbacks: 'default',
  messages: [{ role: 'user', content: prompt }],
});

if (response.stop_reason === 'refusal') {
  console.error('The model declined this request.');
  process.exit(1);
}
const text = response.content.filter((b) => b.type === 'text').map((b) => b.text).join('\n');
const code = text.match(/```(?:javascript|js)\n([\s\S]*?)```/)?.[1];
if (!code) {
  console.error('No code block in the response:\n' + text);
  process.exit(1);
}

const outDir = path.join(here, 'generated');
fs.mkdirSync(outDir, { recursive: true });
const outFile = path.join(outDir, `api.generated.${new Date().toISOString().replace(/[:.]/g, '-')}.spec.js`);
fs.writeFileSync(outFile, `// GENERATED by ${model} - review with labs/12-ai-in-qa/testgen/review-checklist.md before use.\n${code}`);
console.log(`Wrote ${path.relative(root, outFile)}`);
console.log(`Tokens: ${response.usage.input_tokens} in / ${response.usage.output_tokens} out`);
console.log('Next: review it, move it into labs/04-integration-contract/api/tests/, then run  npm run test:api');
